In [1]:
import numpy as np
import pandas as pd

In [2]:
customer=pd.read_csv("customer.csv")

In [3]:
customer.head(15)

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes

In [4]:
customer_1=customer.iloc[: , 2:]

In [5]:
customer_1.sample(10)

review education purchased
8   Average        UG        No
20  Average    School       Yes
31     Poor    School       Yes
3      Good        PG        No
13  Average    School        No
22     Poor        PG       Yes
49     Good        UG        No
12     Poor    School        No
40     Good    School        No
23     Good    School        No

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train , x_test ,y_train ,y_test = train_test_split( customer_1.iloc[:,0:2] , customer_1.iloc[:,-1] , test_size=0.3)

In [8]:
x_train

review education
30  Average        UG
31     Poor    School
42     Good        PG
21  Average        PG
23     Good    School
3      Good        PG
17     Poor        UG
41     Good        PG
6      Good    School
28     Poor    School
38     Good    School
43     Poor        PG
36     Good        UG
39     Poor        PG
25     Good    School
27     Poor        PG
37  Average        PG
19     Poor        PG
13  Average    School
18     Good    School
32  Average        UG
24  Average        PG
29  Average        UG
33     Good        PG
34  Average    School
5   Average    School
12     Poor    School
48     Good        UG
9      Good        UG
2      Good        PG
7      Poor    School
20  Average    School
0   Average    School
10     Good        UG
16     Poor        UG

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
x=[['Poor','Average','Good'],['School','UG','PG']]

In [11]:
oe=OrdinalEncoder(categories=x)

In [12]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [13]:
x_train

review education
30  Average        UG
31     Poor    School
42     Good        PG
21  Average        PG
23     Good    School
3      Good        PG
17     Poor        UG
41     Good        PG
6      Good    School
28     Poor    School
38     Good    School
43     Poor        PG
36     Good        UG
39     Poor        PG
25     Good    School
27     Poor        PG
37  Average        PG
19     Poor        PG
13  Average    School
18     Good    School
32  Average        UG
24  Average        PG
29  Average        UG
33     Good        PG
34  Average    School
5   Average    School
12     Poor    School
48     Good        UG
9      Good        UG
2      Good        PG
7      Poor    School
20  Average    School
0   Average    School
10     Good        UG
16     Poor        UG

In [14]:
oe.transform(x_train)

array([[1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 2.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [0., 0.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [0., 2.],
       [1., 0.],
       [2., 0.],
       [1., 1.],
       [1., 2.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [1., 0.],
       [2., 1.],
       [0., 1.]])

In [15]:
oe.transform(x_test)

array([[2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [0., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.]])

In [16]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()

In [19]:
le.fit(y_train)

LabelEncoder()

In [21]:
le.transform(y_train)


array([0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1])

In [22]:
le.transform(y_test)

array([1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0])